### ISSUE TITLE
🚀  Have a default option to deploy AgentPool during installation

### ISSUE THREAD

**Issue by gautambaghel** [hashicorp/hcp-terraform-operator#217]
### Description

During the deployment of the Terraform Operator, it'd be great to have a 'defaultAgentPool' option (in the values.yml file) to create an agent pool without creating the CR (in other words consuming the CRD) after deployment.

Similar to how Vault Secrets Operator does it: [defaultVaultConnection](https://github.com/hashicorp/vault-secrets-operator/blob/main/chart/values.yaml#L317)

### Potential YAML Configuration (an example values.yml file)
```yaml

replicaCount: 2

operator:
  image:
    repository: hashicorp/terraform-cloud-operator
    pullPolicy: IfNotPresent
    tag: ""
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

defaultAgentPool:
   enabled: true
   name: agent-pool-name
   organization: organization-name
   token:
      secretKeyRef: terraform-cloud-token
      key: token
```

### References

N/A

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
