### ISSUE TITLE
🤔 Choose when runs should be triggered by VCS changes.

### ISSUE THREAD

**Issue by obervinov** [hashicorp/hcp-terraform-operator#314]
### Operator Version, Kind and Kubernetes Version
 - Operator version: 2.1.0
 - Kind: Workspace
 - Kubernetes version: v1.28.2

### YAML Manifest File

```yaml
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  creationTimestamp: "2023-12-29T21:43:46Z"
  finalizers:
  - workspace.app.terraform.io/finalizer
  generation: 1
  name: dns-workspace
  namespace: terraform-operator
spec:
  agentPool:
    name: kubernetes-tfc-agent-pool
  allowDestroyPlan: true
  applyMethod: manual
  description: For managing the DNS records
  executionMode: agent
  name: dns-workspace
  notifications:
  - emailUsers:
    - obervinov@example.com
    enabled: true
    name: 'Terraform Cloud: DNS'
    triggers:
    - run:applying
    - assessment:check_failure
    - run:completed
    - assessment:drifted
    - run:errored
    - assessment:failed
    - assessment:failed
    type: email
  organization: ***
  tags:
  - dns
  - terraform-operator
  - automatic-deployment
  terraformVersion: 1.6.6
  token:
    secretKeyRef:
      key: token
      name: tfc-operator
  versionControl:
    oAuthTokenID: ***
    repository: infrastructure
  workingDirectory: infra/dns
```

### Question

In the Web UI settings of Terraform Cloud, I can override the `VCS Triggers` setting by setting the parameter to `Only trigger runs when files in specified paths change`.
This allows for multi-repository setups with different workspaces to avoid triggering all workspaces at once when a commit is made to the repository. However, I don't see support for this functionality in the [API specification](https://github.com/hashicorp/terraform-cloud-operator/blob/main/docs/api-reference.md#workspacespec) through the CRD Workspace.
Is it possible to change the value of `VCS Triggers`, or will I have to abandon the Terraform operator in favor of manually creating workspaces through the web UI?
<img width="1149" alt="Снимок экрана 2023-12-30 в 13 30 25" src="https://github.com/hashicorp/terraform-cloud-operator/assets/49606362/872756e4-b2c0-4d88-ac3f-3594a0ce0744">

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
