### ISSUE TITLE
How to configure Assume Role when setting up AWS configuration? 🤔 

### ISSUE THREAD

**Issue by sabinayakc** [hashicorp/hcp-terraform-operator#463]
### Operator Version, Kind and Kubernetes Version
 - Operator version: latest
 - Kind: Workspace 
 - Kubernetes version: 1.30 

### YAML Manifest File

```yaml
 environmentVariables:
    - name: AWS_DEFAULT_REGION
      sensitive: false
      valueFrom:
        configMapKeyRef:
          name: aws-configuration
          key: region
    - name: AWS_ACCESS_KEY_ID
      sensitive: false
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      sensitive: true
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: AWS_SECRET_ACCESS_KEY

--- ROLE ARN -- ???
```

### Output Log

N/A

### Kubectl Outputs

N/A
### Question

How do I use Assume Role with terraform cloud operator? How can I pass that while creating a workspace and module?
Or Do I have to pass the configuration from a config file or secret file?

Want to achieve the following configuration
```hcl
provider "aws" {
  region  = "us-east-2"
  assume_role {
    role_arn = "arn:aws:iam::XXXX:role/XXXXX"
  }
}
```

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
