### ISSUE TITLE
🤔 Provider Block is required for deploying azurerm resource using Module object(HCP Terraform operator v2)

### ISSUE THREAD

**Issue by gogondi1** [hashicorp/hcp-terraform-operator#537]
### Operator Version, Kind and Kubernetes Version
 - Operator version: v2
 - Kind: Module 
 - Kubernetes version: 1.29

### YAML Manifest File

```yaml
# Copy-paste your YAML manifest here
apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: greetings3
spec:
  organization: xxxx-xxxx-xxx
  token:
    secretKeyRef:
      name: terraformrc
      key: token
  destroyOnDeletion: true
  module:
    source: app.terraform.io/xxxx-xxxx-xxxx/rg/azurerm
    version: 6.1.0
  outputs:
    - name: resource_group_id
  variables:
    - name: client_name 
    - name: environment
    - name: location
    - name: stack
  workspace:
    name: greetings
```

### Question

Error: Invalid provider configuration
Provider "registry.terraform.io/hashicorp/azurerm" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider documentation. How to resolve this while creating a azurerm 
module using HCP Terraform CRD operator v2  using object "Module"
### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
