### ISSUE TITLE
🚀 Allow Setting EnvVars

### ISSUE THREAD

**Issue by camrossi** [hashicorp/hcp-terraform-operator#547]
### Description
My cluster sits behind a proxy and I would like to be able to set envVars for my operator deployment. 
This should be a trivial change in the deployment template.

### Potential YAML Configuration
N/A

### References
N/A

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by arybolovlev** [comment]
Hi @camrossi,

Could you please share an example of how the resulting deployment should look like?

Thank you.

**Comment by camrossi** [comment]
Sure the relevant part would be this

```
      spec:
        containers:
        - env:
          - name: https_proxy
            value: http://proxy:80
          - name: http_proxy
            value: http://proxy:80
          - name: no_proxy
            value: localhost,domain123
```

Many Helm Charts implement this already for example a copy paste from the Prometheus Operator one:

```
          env:
          {{- range $key, $value := .Values.prometheusOperator.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
```

And the helm value file would look like

``
prometheusOperator
    env:
      GOGC: "30"
```
