### ISSUE TITLE
🚀 Import/link to current/existing workspace

### ISSUE THREAD

**Issue by diepes** [hashicorp/hcp-terraform-operator#551]
### Description
We would like to deploy a workspace CRD that uses an existing workspace and start managing it.

Looking at
(https://developer.hashicorp.com/terraform/cloud-docs/integrations/kubernetes/api-reference#workspacespec)

The suggestion is to add a optional "workspace-tfc-id"
When set the hcp operator should use the existing workspace thus preserving the state and allowing migration to the operator for the workspace management.

### Potential YAML Configuration
Could be annotation or a value under spec.
e.g. of annotation for existing workspace: ID: "ws-abcZwwwww"

workspace.yaml
```yaml
# This manifest creates a Workspace in Terraform Cloud.
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: "git-repo-testing"
  namespace: tfworkspace-poc
  annotations:
    workspace.app.terraform.io/run-new: "true"
    workspace.app.terraform.io/run-type: "plan"
    workspace.app.terraform.io/workspace-tfc-id: "ws-abcZwwwww"
spec:
     ...
```

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
