### ISSUE TITLE
🚀Add possibility to use also existing agent pool in agentpool.yaml CR configuration

### ISSUE THREAD

**Issue by zoli-opslogic** [hashicorp/hcp-terraform-operator#583]
### Potential YAML Configuration
```yaml
spec:
  agentDeployment:
    replicas: 1
    spec:
      containers:
        - image: hashicorp/tfc-agent:1.20
          name: tfc-agent
  agentTokens:
    - name: agents-eks-token
  name: agents-eks
  organization: MytfOrg

  existingAgentPool: true    <--- in this case it should check based on the name of the agent pool if it exists or not and use the ID of that agent pool.

OR

  existingAgentPoolID: apool-5739FGHfhryfj355sd   <--- in this case the agent pool name is no longer required and just use the provided agent pool ID.
```

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
